name: build and push docker image to ECR
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # Setting an environment variable with the value of a configuration variable
  ECR_IMAGE: ${{ vars.ECR_IMAGE }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  # ECR_CLUSTER: ${{ vars.ECR_CLUSTER }}

jobs:
  build:
    name: Build
    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 880757820269.dkr.ecr.ap-southeast-1.amazonaws.com

      # - name: Build and push Docker image to Amazon ECR
      #   run: |

      - name: Build Docker image
        run: |
          docker build -t ${{ env.ECR_IMAGE }}:${{ github.sha }} .

      - name: Tag Docker image
        run: |
          docker tag ${{ env.ECR_IMAGE }}:${{ github.sha }} ${{ env.ECR_REGISTRY }}/${{ env.ECR_IMAGE }}:${{ github.sha }}
          docker tag ${{ env.ECR_IMAGE }}:${{ github.sha }} ${{ env.ECR_REGISTRY }}/${{ env.ECR_IMAGE }}:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_IMAGE }}:${{ github.sha }}
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_IMAGE }}:latest
